version: "0.1"

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whowolf
    ports:
      - "3306:3306"
